Добавляет наставника
htmlacademy-htmlcss/2179015-sedona-35 pull request #1
Opened 2022-09-21 05:45 UTC by Ilchenko1986

2022-09-21 09:00 UTC, baronin commented on Readme.md
> +* Наставник: `Ярослав Баронин`.
А можешь сделать так же и на меня ссылку? По аналогии как у тебя :)

2022-09-21 09:01 UTC, baronin requested changes
Супер что с гитом разобралась ! :)

2022-09-22 10:08 UTC, Ilchenko1986 commented on Readme.md
> +* Наставник: `Ярослав Баронин`.
Готово!)

2022-09-23 06:32 UTC, baronin approved these changes
Well done! :)

2022-09-23 06:33 UTC, merged