Базовая стилизация страниц
htmlacademy-htmlcss/2179015-sedona-35 pull request #4
Opened 2022-10-15 10:19 UTC by Ilchenko1986

2022-10-15 21:20 UTC, baronin requested changes
https://validator.w3.org/nu/#file
Много ошибок в валидаторе, поправь пожалуйста 
<img width="496" alt="image" src="https://user-images.githubusercontent.com/20131942/196007995-f632bb83-e024-4ca7-b604-1d64967a8816.png">

2022-10-15 21:20 UTC, baronin commented on styles/styles.css
> +    Font-size: 20px;
Давай стараться писать код в единообразном стиле Font-size - в проекте мы пишем свойства все с маленькой буквы

2022-10-15 21:20 UTC, baronin commented on catalog.html
> +        <section class="mailing">
newsletter - хорошо подходило :)

И вроде у тебя этот блок готов на странице index, если он такой же, просто вставь разметку сюда

2022-10-15 21:20 UTC, baronin commented on catalog.html
> +                    <a class="product-card-button batton" href="#">В Избранное</a>
batton  так будет правильно -> button

2022-10-15 21:20 UTC, baronin commented on index.html
> +            <img src="images/welcome.svg" width="187.7" height="44.7" alt="Welcome">
мы не используем дроби 44.7, нужно округлять 45 будет хорошо

2022-10-15 21:20 UTC, baronin commented on catalog.html
> +                    <a class="product-card-button batton" href="#">В Избранное</a>
Это кнопка, просто будет вызвано событие, на другую страницу нас не будет вести

2022-10-15 21:20 UTC, baronin commented on catalog.html
>          </section>
Секция закрыта, но не ясно где она открыта

2022-10-15 21:20 UTC, baronin commented on catalog.html
>                      <p class="hotels-stars hotels-stars-4>
не закрыт тег

2022-10-16 11:06 UTC, Ilchenko1986 commented on catalog.html
> +        <section class="mailing">
Для класса newsletter в CSS я добавила фоновое изображение, а на странице каталога его нет. Поэтому я изменила название класса и указала новое правило для него (без фоновой картинки)

2022-10-20 14:09 UTC, merged